<script>
  import BlogList from "$lib/assets/components/blog/BlogList.svelte";
</script>

<div class="blogHeader">
  <h1>Blog</h1>
  <div class="subTitle">
    Use this div to add some text to your header, like "Find here our great blog
    posts that definitely weren't just generated by an AI."
  </div>
</div>

<div class="blogPage">
  <slot />

  <!-- <BlogList data={$page.data} /> -->
</div>

<style>
  @font-face {
    font-family: "CormorantGaramond";
    src: url("/fonts/CormorantGaramond-LightItalic.ttf") format("truetype");
  }
  h1 {
    padding: 20px;
    font-family: var(--default-font);
    font-style: normal;
    font-weight: 700;
    font-size: 40px;
    line-height: 47px;

    color: var(--primary--deep-dark);
  }

  .subTitle {
    font-family: var(--alt-font);
    font-style: italic;
    font-weight: 400;
    font-size: 18px;

    color: var(--primary-color);

    padding: 0px 20px;
  }

  .blogHeader {
    min-height: 150px;
    background-color: var(--base-bg);
    padding-bottom: 20px;
  }

  .blogPage {
    display: flex;
    flex-orientation: column;
    gap: 10px;
    padding: 20px;
  }
</style>
